# Change these first
owner: revinet-status # Your GitHub organization or username, where this repository lives
repo: k-fediverse-status # The name of this repository

# following check must be present:
# __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
# TODO: ABC order
# name에 한글 입력 안 됩니다. 라틴알파벳 타파해야... (아무말)

sites:
  - name: planet.moe
    url: https://planet.moe/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: amaurot.city
    url: https://amaurot.city/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: Aniwork Network
    url: https://ani.work/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: ChalkBoard
    url: https://chalk.moe/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: Dimension
    url: https://dimension.host/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: naru.cafe DON
    url: https://don.naru.cafe/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: HotoMoe
    url: https://hoto.moe/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
      - 0
      - 404
  - name: Misskey.lapy
    url: https://k.lapy.link/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: madost.one
    url: https://madost.one/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: masost.one
    url: https://masost.one/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: mustard.blog
    url: https://mustard.blog/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: qdon.space
    url: https://qdon.space/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: Old Sharlayan
    url: https://old.sharlayan.city/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: SiFNet
    url: https://social.silicon.moe/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: YuruToot
    url: https://toot.funami.tech/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: uri.life
    url: https://uri.life/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: yoyang.one
    url: https://yoyang.one/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: Bunbers
    url: https://bunbers.org/nodeinfo/2.0.json
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: Twingyeo
    url: https://twingyeo.kr/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: FediverseWiki
    url: https://wiki.mastodon.kr/w/api.php?action=query&meta=siteinfo&siprop=statistics&format=json
  - name: jmm
    url: https://jmm.kr/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: maratang.life
    url: https://maratang.life/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: kurry.social
    url: https://kurry.social/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: pointless.chat
    url: https://pointless.chat/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: muri.network
    url: https://muri.network/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: netsphere.one
    url: https://netsphere.one/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: mnetwork.co.kr
    url: https://mastodon.mnetwork.co.kr/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: t.chadole.com
    url: https://t.chadole.com/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: krpgpub.net
    url: https://krpgpub.net/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: bakedbean.xyz
    url: https://bakedbean.xyz/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: kono.pub
    url: https://kono.pub/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: trpg-o.xyz
    url: https://trpg-o.xyz/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'
  - name: s.mysw.moe
    url: https://s.mysw.moe/nodeinfo/2.0
    __dangerous__body_down_if_text_missing: '"protocols":["activitypub"]'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.fediverse.kr
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "K-연합우주 상태창"
  introMessage: "[Upptime](https://github.com/upptime/upptime)으로 보는 연합우주 서버상태창. 추가/삭제 문의는 [깃헙](https://github.com/revinet-status/k-fediverse-status/issues) 또는 [이메일](mailto:bug@phab.revi.dev)로 부탁드립니다."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
